name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-02"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzg5NWRmOWItNDY1Yy00YTUxLThlN2YtODhmZjQ2YWY5Y2ZjIiwidGVuYW50X2lkIjoiOTNkZTEzYWUzZDIzM2QzNzllZTBlMTBkZDcxZDljMzg4ZmM3NThlYTY5MzkwZGIwYTkyNGRiOGI4Y2YzMDkzNSIsImludGVybmFsX3NlY3JldCI6ImMzZWE3OWZjLTgxNjQtNDMyZS1iOTc4LTI1ODZhNDlmMjY4ZSJ9.brEr0JjxOp65K0I8E0TZtzXySX8RXDBUFeshbazJo78"
# DIRECT_URL="<YOUR_DATABASE_CONNECTION_STRING>"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1